"""New Migration

Revision ID: 6efcab067d21
Revises: a2b05861fae2
Create Date: 2023-06-08 08:50:49.065134

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6efcab067d21'
down_revision = 'a2b05861fae2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('message', sa.String(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_index('ix_post_id', table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('time_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='post_pkey')
                    )
    op.create_index('ix_post_id', 'post', ['id'], unique=False)
    op.drop_table('test_table')
    # ### end Alembic commands ###
